Aulas/force-app/main/default/objects/ProdutoEstoque__c/ProdutoEstoque__c.object-meta.xml
<CustomObject>
    <label>Produto do Estoque</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos dos Estoques</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Aulas/force-app/main/default/objects/ProdutoEstoque__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Aulas/force-app/main/default/classes/Pedido_NotifyCustomer.cls
public with sharing class Pedido_NotifyCustomer extends SObjectTrigger {
    public static Boolean disableTrigger = false;
    private static Boolean running = false;
    
    public override String getRunningClassName() {
        return Pedido_NotifyCustomer.class.getName();
    }

    //right now, this class is being invoked only by AFTER INSERT
    public override Boolean getIsToProcess(SObject oldRecord, SObject newRecord) {
        if (disableTrigger || disableTriggerSettings || running) {
            return false;
        }
        
        running = true;
        
        return true;
    }

    public override void executeTrigger(List<SObject> records) {
        for (ProdutoEstoque__c record : (List<ProdutoEstoque__c>) records) {
            executeTrigger(record);
        }
    }

    private void executeTrigger(ProdutoEstoque__c record) {
        if (record.Quantidade__c == null) {
            record.Quantidade__c.addError('Required field');
        } else if (record.Quantidade__c <= 0) {
            record.Quantidade__c.addError('It must be greater than 0');
        }
    }
}