Aulas/force-app/main/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <label>Estoque</label>
    <nameField>
        <displayFormat>EST-{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estoques</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aulas/force-app/main/default/objects/Farmacia__c/Farmacia__c.object-meta.xml
<CustomObject>
    <label>Farmácia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmácias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aulas/force-app/main/default/objects/Farmacia__c/fields/Estoque__c.field-meta.xml
<CustomField>
    <fullName>Estoque__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Estoque</label>
    <referenceTo>Estoque__c</referenceTo>
    <relationshipLabel>Farmácias</relationshipLabel>
    <relationshipName>Farmacias</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Aulas/force-app/main/default/objects/Pedido__c/Pedido__c.object-meta.xml
<CustomObject>
    <label>Pedido</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Aulas/force-app/main/default/objects/Pedido__c/fields/Farmacia__c.field-meta.xml
<CustomField>
    <fullName>Farmacia__c</fullName>
    <label>Farmácia</label>
    <referenceTo>Farmacia__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Aulas/force-app/main/default/objects/Pedido__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
            </value>
            <value>
                <fullName>Parcial</fullName>
            </value>
            <value>
                <fullName>Completo</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Aulas/force-app/main/default/objects/Produto__c/Produto__c.object-meta.xml
<CustomObject>
    <label>Produto</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aulas/force-app/main/default/objects/ProdutoEstoque__c/ProdutoEstoque__c.object-meta.xml
<CustomObject>
    <label>Produto do Estoque</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos dos Estoques</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Aulas/force-app/main/default/objects/ProdutoEstoque__c/fields/Estoque__c.field-meta.xml
<CustomField>
    <fullName>Estoque__c</fullName>
    <label>Estoque</label>
    <referenceTo>Estoque__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Aulas/force-app/main/default/objects/ProdutoEstoque__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <label>Produto</label>
    <referenceTo>Produto__c</referenceTo>
    <relationshipLabel>Estoques</relationshipLabel>
    <relationshipName>Estoques</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Aulas/force-app/main/default/objects/ProdutoEstoque__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Aulas/force-app/main/default/objects/ProdutoPedido__c/ProdutoPedido__c.object-meta.xml
<CustomObject>
    <label>Produto do Pedido</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos dos Pedidos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Aulas/force-app/main/default/objects/ProdutoPedido__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Pedido__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Aulas/force-app/main/default/objects/ProdutoPedido__c/fields/Pendencia__c.field-meta.xml
<CustomField>
    <fullName>Pendencia__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pendência</label>
    <type>Checkbox</type>
</CustomField>

Aulas/force-app/main/default/objects/ProdutoPedido__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <label>Produto</label>
    <referenceTo>Produto__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Aulas/force-app/main/default/classes/Pedidos.cls
/**
 * recebe id de pedido OU lista de id de pedidos
validar se tem TODOS os produtos em estoque (qtd pedida <= qtd em estoque)
se tiver:
   atualizar quantidade em estoque
   atualizar status do pedido para Completo
se não tiver ALGUM:
   atualiza quantidade em estoque de todos que tem em estoque
   atualiza status do pedido para Parcial
   atualiza campo Pendencia no produto do pedido que não tem estoque para TRUE
 */
public class Pedidos {
    public static void valida(Id pedidoId) {
        //BUSCANDO INFORMAÇÕES - START
        //SOQL - pedido
        Pedido__c pedido = [
            SELECT Id, Farmacia__r.Estoque__c, (SELECT Id, Quantidade__c, Pendencia__c, Produto__c FROM Produtos__r)
            FROM Pedido__c
            WHERE Id = :pedidoId
        ];
        //produtos do pedido
        List<ProdutoPedido__c> produtosPedido = pedido.Produtos__r;

        //SOQL - estoque
        Estoque__c estoque = [
            SELECT Id, (SELECT Id, Quantidade__c, Produto__c FROM Produtos__r)
            FROM Estoque__c
            WHERE Id = :pedido.Farmacia__r.Estoque__c
        ];
        //produtos do estoque
        List<ProdutoEstoque__c> produtosEstoque = estoque.Produtos__r;
        //BUSCANDO INFORMAÇÕES - END

        //ATUALIZAÇÃO DE ESTOQUE E PENDENCIA
         for (ProdutoPedido__c pp : produtosPedido) { //para cada produto do pedido
            for (ProdutoEstoque__c pe : produtosEstoque) { //para cada produto do estoque
                if (pp.Produto__c == pe.Produto__c) { //procura o produto relacionado no estoque
                    if (pe.Quantidade__c == 0) { //encontrou, verifica se a quantidade é 0
                        pp.Pendencia__c = true; //se sim, pendencia = true
                    } else { //se a quantidade não é 0, ou seja, tem em estoque
                        if (pp.Quantidade__c <= pe.Quantidade__c) { //verifica se a quantidade pedida tem em estoque
                            pe.Quantidade__c = pe.Quantidade__c - pp.Quantidade__c; //atualiza o estoque
                        } else { //não tem a quantidade suficiente em estoque
                            pp.Pendencia__c = true; //NAÕ VENDE O PRODUTO, MARCA COM PENDENCIA, GERENTE SE VIRA
                        }
                    }
                    break; //já encontrou o produto no estoque, já realizou a lógica toda e não preciso continuar executando
                } else { //ainda não achei o produto do pedido no estoque
                    //esse ELSE é inútil, pode ser removido.
                }
            }
         }

         update produtosPedido; //DML - atualiza os produtos do pedido (campo Pendencia__c)
         update produtosEstoque; //DML - atualiza as quantidades em estoque

         //SOQL - busca o pedido e os produtos relacionados onde Pendencia__c = true
         pedido = [
            SELECT 
                Id, 
                Farmacia__r.Estoque__c, 
                Status__c,
                (SELECT Id, Quantidade__c, Pendencia__c FROM Produtos__r WHERE Pendencia__c = true) //produtos relacionados
            FROM Pedido__c
            WHERE Id = :pedidoId
        ];

        if (pedido.Produtos__r.isEmpty()) { //se nenhum produto do pedido possui pendência
            pedido.Status__c = 'Completo'; //atualiza status para completo
        } else { //se algum produto do pedido possui pendência
            pedido.Status__c = 'Parcial'; //atualiza status para parcial
        }

        update pedido; //DML para atualizar o pedido (campo status);

    }
}