Aulas/force-app/main/default/objects/Produto__c/Produto__c.object-meta.xml
<CustomObject>
    <label>Produto</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Aulas/force-app/main/default/objects/ProdutoEstoque__c/ProdutoEstoque__c.object-meta.xml
<CustomObject>
    <label>Produto do Estoque</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos dos Estoques</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Aulas/force-app/main/default/objects/ProdutoEstoque__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>Product name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Aulas/force-app/main/default/objects/ProdutoEstoque__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <label>Produto</label>
    <referenceTo>Produto__c</referenceTo>
    <relationshipLabel>Estoques</relationshipLabel>
    <relationshipName>Estoques</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Aulas/force-app/main/default/classes/ProdutoEstoque_UpdateProductName.cls
public with sharing class ProdutoEstoque_UpdateProductName extends SObjectTrigger {
    public static Boolean disableTrigger = false;
    private static Boolean running = false;

    public override String getRunningClassName() {
        return ProdutoEstoque_UpdateProductName.class.getName();
    }

    //right now, this class is being invoked only by BEFORE INSERT
    public override Boolean getIsToProcess(SObject oldRecord, SObject newRecord) {
        if (disableTrigger || disableTriggerSettings || running) {
            return false;
        }

        running = true;

        return true;
    }

    public override void executeTrigger(List<SObject> records) {
        Map<Id, Product2> products = new Map<Id, Product2>(
            [SELECT Id, Name FROM Product2 WHERE Id IN :Utils.buildMapByIdField(records, ProdutoEstoque__c.Produto__c).keySet()]
        );

        executeTrigger(records, products);
    }
    
    private void executeTrigger(List<SObject> records, Map<Id, Product2> products) {
        for (ProdutoEstoque__c record : (List<ProdutoEstoque__c>) records) {
            record.ProductName__c = products.get(record.Produto__c).Name;
        }
    }
}